services:
  endee-oss:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: endee-oss
    ports:
      - "8080:8080"
    ulimits:
      nofile: 100000
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"
    environment:
      NDD_NUM_THREADS: 0
    volumes:
      - endee-data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  codedna:
    build:
      context: ./codedna
      dockerfile: Dockerfile
    container_name: codedna-ui
    ports:
      - "8501:8501"
    environment:
      - ENDEE_HOST=endee-oss
      - ENDEE_PORT=8080
      - EMBEDDING_MODEL=TaylorAI/bge-micro-v2
      - CODE_EMBEDDING_MODEL=microsoft/codebert-base
    depends_on:
      endee-oss:
        condition: service_healthy
    restart: unless-stopped

volumes:
  endee-data:
